platform :ios, '8.0'
use_frameworks!

target 'HuanYinSwift' do
pod 'Alamofire'
pod 'ObjectMapper'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'XLPagerTabStrip', '~> 2.0'
pod 'MJRefresh'
pod 'Ono'
pod 'TTTAttributedLabel'
pod '1PasswordExtension', '~> 1.6.1'
pod 'SnapKit'
pod 'SDWebImage', '~>3.7'
pod 'UITableView+FDTemplateLayoutCell', '~> 1.4.beta'
pod 'UIActionSheet+Blocks'
pod 'UIAlertController+Blocks'
pod 'UIBarButtonItem-Badge', :git => 'https://github.com/mikeMTOL/UIBarButtonItem-Badge.git'
pod 'ZBarSDK', '~> 1.3.1'
pod 'DrawerController'

end
